queue_rules:
  - name: default
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body | get_section("## Summary", "") }}

pull_request_rules:
  - name: auto-queue when CI passes
    conditions:
      - base = main
      - check-success = CI
    actions:
      queue:
        name: default
